version: '3.4'


services:
  postgres_main_server:
    container_name: chatAppDB
    image: postgres
    ports:
      - 8002:5432
    volumes:
      - chatAppVolume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: divyansh
      POSTGRES_DB: chatapp
      POSTGRES_PASSWORD: divyansh

  redis:
    container_name: chatAppCache
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - chatAppVolume:/var/lib/redis/data

  cassandra:
    image: cassandra:latest
    container_name: cassandra_chatApp
    ports:
      - "7001:9042"
    volumes:
      - chatAppVolume:/var/lib/cassandra/data2
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_START_RPC=true
  
  postgres_socket_server:
    container_name: socketServerDB
    image: postgres
    ports:
      - 8003:5432
    volumes:
      - chatAppVolume:/var/lib/postgresql2/data
    environment:
      POSTGRES_USER: divyansh
      POSTGRES_DB: chatapp
      POSTGRES_PASSWORD: divyansh


volumes:
  chatAppVolume: