type User{
    id: ID!
    name: String!
    username: String!
    password: String!
    friends: Int
    requested: Int
    profilePictureURL:String
    Bio: String
}
type UserToRoom{
        roomID: String!
        friendID: number!,
}

type Queries{

    getAllUsers(search:String!):[User]
    getUser(username:String!):User
    getFriendsData(userId:Int!):[User]
    getUserToRoomData(userId:Int!):[UserToRoom]
}

input createUserInput{
    name: String!
    username: String!
    password: String!
    friends: Int
    requested: Int
    number_of_posts: Int
    profilePictureURL:String
    Bio: String
}
input updateUser{
    name: String!
    username: String!
    password: String
    friends: Int
    requested: Int
    number_of_posts: Int
    profilePictureURL:String
    Bio: String
}
type mutation{
    #create user
    createUser(input:createUserInput):Boolean
    #update user
    updateUser(input:updateUser,user:String!):Boolean
}